"""adicionar sprite ao pokemon

Revision ID: 473718d12ea5
Revises: 9dc04a17bb68
Create Date: 2026-05-23 09:28:16.012304

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "473718d12ea5"
down_revision: Union[str, Sequence[str], None] = "9dc04a17bb68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pokemon_species",
        sa.Column("front_default_sprite", sa.String(length=1000), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon_species", "front_default_sprite")
    # ### end Alembic commands ###
