"""initial

Revision ID: 9dc04a17bb68
Revises:
Create Date: 2026-04-27 16:13:16.642021

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dc04a17bb68"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("power", sa.Integer(), nullable=False),
        sa.Column("accuracy", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("pp", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "NORMAL",
                "FIRE",
                "WATER",
                "GRASS",
                "ELECTRIC",
                "ICE",
                "FIGHTING",
                "POISON",
                "GROUND",
                "FLYING",
                "PSYCHIC",
                "BUG",
                "ROCK",
                "GHOST",
                "DRAGON",
                "DARK",
                "STEEL",
                "FAIRY",
                "SHADOW",
                name="pokemon_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint("accuracy >= 0"),
        sa.CheckConstraint("power >= 0"),
        sa.CheckConstraint("pp >= 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_movements_name"),
    )
    op.create_index(op.f("ix_movements_name"), "movements", ["name"], unique=False)
    op.create_table(
        "pokemon_species",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("hp", sa.Integer(), nullable=False),
        sa.Column("attack", sa.Integer(), nullable=False),
        sa.Column("defense", sa.Integer(), nullable=False),
        sa.Column("special_attack", sa.Integer(), nullable=False),
        sa.Column("special_defense", sa.Integer(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.CheckConstraint("attack BETWEEN 1 AND 255"),
        sa.CheckConstraint("defense BETWEEN 1 AND 255"),
        sa.CheckConstraint("hp BETWEEN 1 AND 255"),
        sa.CheckConstraint("special_attack BETWEEN 1 AND 255"),
        sa.CheckConstraint("special_defense BETWEEN 1 AND 255"),
        sa.CheckConstraint("speed BETWEEN 1 AND 255"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", name="uq_pokemon_species_external_id"),
        sa.UniqueConstraint("name", name="uq_pokemon_species_name"),
    )
    op.create_index(
        op.f("ix_pokemon_species_name"), "pokemon_species", ["name"], unique=False
    )
    op.create_table(
        "pokemon_specie_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("specie_id", sa.Integer(), nullable=False),
        sa.Column("movement_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["movement_id"], ["movements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["specie_id"], ["pokemon_species.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("specie_id", "movement_id", name="uq_specie_movement"),
    )
    op.create_index(
        op.f("ix_pokemon_specie_movements_movement_id"),
        "pokemon_specie_movements",
        ["movement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pokemon_specie_movements_specie_id"),
        "pokemon_specie_movements",
        ["specie_id"],
        unique=False,
    )
    op.create_table(
        "pokemon_specie_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("specie_id", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "NORMAL",
                "FIRE",
                "WATER",
                "GRASS",
                "ELECTRIC",
                "ICE",
                "FIGHTING",
                "POISON",
                "GROUND",
                "FLYING",
                "PSYCHIC",
                "BUG",
                "ROCK",
                "GHOST",
                "DRAGON",
                "DARK",
                "STEEL",
                "FAIRY",
                "SHADOW",
                name="pokemon_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.CheckConstraint("slot IN (1, 2)"),
        sa.ForeignKeyConstraint(
            ["specie_id"], ["pokemon_species.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("specie_id", "slot", name="uq_specie_type_slot"),
        sa.UniqueConstraint("specie_id", "type", name="uq_specie_type_value"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pokemon_specie_types")
    op.drop_index(
        op.f("ix_pokemon_specie_movements_specie_id"),
        table_name="pokemon_specie_movements",
    )
    op.drop_index(
        op.f("ix_pokemon_specie_movements_movement_id"),
        table_name="pokemon_specie_movements",
    )
    op.drop_table("pokemon_specie_movements")
    op.drop_index(op.f("ix_pokemon_species_name"), table_name="pokemon_species")
    op.drop_table("pokemon_species")
    op.drop_index(op.f("ix_movements_name"), table_name="movements")
    op.drop_table("movements")
    # ### end Alembic commands ###
